//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobNest
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplication
    {
        public int JobApplicationId { get; set; }
        public int EmployeeId { get; set; }
        public int JobId { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public string Resume { get; set; }
        public string ApplicationStatus { get; set; }
    }
}
