//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobNest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JobNestEntities : DbContext
    {
        public JobNestEntities()
            : base("name=JobNestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<JobApplication> JobApplications { get; set; }
        public virtual DbSet<JobPosting> JobPostings { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
    
        public virtual int CompanyOperations(Nullable<int> id, Nullable<int> companyId, string companyName, string companyAddress, string companyEmail, string companyPhone, string username, string password, string loginType)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("CompanyName", companyName) :
                new ObjectParameter("CompanyName", typeof(string));
    
            var companyAddressParameter = companyAddress != null ?
                new ObjectParameter("CompanyAddress", companyAddress) :
                new ObjectParameter("CompanyAddress", typeof(string));
    
            var companyEmailParameter = companyEmail != null ?
                new ObjectParameter("CompanyEmail", companyEmail) :
                new ObjectParameter("CompanyEmail", typeof(string));
    
            var companyPhoneParameter = companyPhone != null ?
                new ObjectParameter("CompanyPhone", companyPhone) :
                new ObjectParameter("CompanyPhone", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var loginTypeParameter = loginType != null ?
                new ObjectParameter("LoginType", loginType) :
                new ObjectParameter("LoginType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CompanyOperations", idParameter, companyIdParameter, companyNameParameter, companyAddressParameter, companyEmailParameter, companyPhoneParameter, usernameParameter, passwordParameter, loginTypeParameter);
        }
    
        public virtual int EmployeeOperations(Nullable<int> id, Nullable<int> employeeId, string employeeName, Nullable<int> employeeAge, string employeeGender, string employeeAddress, string employeePhone, string employeeEmail, string employeeQualification, string employeeSkills, Nullable<int> employeeExperience, string employeePhoto, string employeeStatus, string username, string password, string loginType)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            var employeeNameParameter = employeeName != null ?
                new ObjectParameter("EmployeeName", employeeName) :
                new ObjectParameter("EmployeeName", typeof(string));
    
            var employeeAgeParameter = employeeAge.HasValue ?
                new ObjectParameter("EmployeeAge", employeeAge) :
                new ObjectParameter("EmployeeAge", typeof(int));
    
            var employeeGenderParameter = employeeGender != null ?
                new ObjectParameter("EmployeeGender", employeeGender) :
                new ObjectParameter("EmployeeGender", typeof(string));
    
            var employeeAddressParameter = employeeAddress != null ?
                new ObjectParameter("EmployeeAddress", employeeAddress) :
                new ObjectParameter("EmployeeAddress", typeof(string));
    
            var employeePhoneParameter = employeePhone != null ?
                new ObjectParameter("EmployeePhone", employeePhone) :
                new ObjectParameter("EmployeePhone", typeof(string));
    
            var employeeEmailParameter = employeeEmail != null ?
                new ObjectParameter("EmployeeEmail", employeeEmail) :
                new ObjectParameter("EmployeeEmail", typeof(string));
    
            var employeeQualificationParameter = employeeQualification != null ?
                new ObjectParameter("EmployeeQualification", employeeQualification) :
                new ObjectParameter("EmployeeQualification", typeof(string));
    
            var employeeSkillsParameter = employeeSkills != null ?
                new ObjectParameter("EmployeeSkills", employeeSkills) :
                new ObjectParameter("EmployeeSkills", typeof(string));
    
            var employeeExperienceParameter = employeeExperience.HasValue ?
                new ObjectParameter("EmployeeExperience", employeeExperience) :
                new ObjectParameter("EmployeeExperience", typeof(int));
    
            var employeePhotoParameter = employeePhoto != null ?
                new ObjectParameter("EmployeePhoto", employeePhoto) :
                new ObjectParameter("EmployeePhoto", typeof(string));
    
            var employeeStatusParameter = employeeStatus != null ?
                new ObjectParameter("EmployeeStatus", employeeStatus) :
                new ObjectParameter("EmployeeStatus", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var loginTypeParameter = loginType != null ?
                new ObjectParameter("LoginType", loginType) :
                new ObjectParameter("LoginType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EmployeeOperations", idParameter, employeeIdParameter, employeeNameParameter, employeeAgeParameter, employeeGenderParameter, employeeAddressParameter, employeePhoneParameter, employeeEmailParameter, employeeQualificationParameter, employeeSkillsParameter, employeeExperienceParameter, employeePhotoParameter, employeeStatusParameter, usernameParameter, passwordParameter, loginTypeParameter);
        }
    
        public virtual ObjectResult<Login_Result> Login(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Login_Result>("Login", usernameParameter, passwordParameter);
        }
    }
}
