//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobNest
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPosting
    {
        public int JobId { get; set; }
        public int CompanyId { get; set; }
        public string JobTitle { get; set; }
        public int ExperienceRequired { get; set; }
        public string RequiredSkills { get; set; }
        public string JobLocation { get; set; }
        public string RequiredQualification { get; set; }
        public decimal Salary { get; set; }
        public System.DateTime PostDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string JobStatus { get; set; }
    }
}
